name: playground
description: A new Flutter project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shake:
    # https://github.com/deven98/shake/pull/6
    git: https://github.com/maxlapides/shake.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  mfsao: ^0.2.0

flutter:
  uses-material-design: true
