name: playground
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  shake: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mfsao: ^0.1.3

flutter:
  uses-material-design: true
